### ISSUE TITLE
captcha認証部分をdiscord apiで直接叩く

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-backend#4]
まあipcs使ったやり方もいいけど、こっちの方が早いと思うし、ボットが落ちていても、ロール付与できる。

**Comment by tasuren** [comment]
めんどくさいな。
あと、Botが落ちてたら認証ページに行けないと思うんだけど。
まあやるとしたら、hikariっていうライブラリの`RESTApp`を使うと思う。

**Comment by tuna2134** [comment]
> めんどくさいな。
> あと、Botが落ちてたら認証ページに行けないと思うんだけど。
> まあやるとしたら、hikariっていうライブラリの`RESTApp`を使うと思う。

確かに
まあここは僕がやってもいいよ
(最悪、discord.pyのHttpClient使えばいいし)

**Comment by tasuren** [comment]
やったらやったでコードが複雑になるとなる上に、Botが落ちてたらどっちみち認証いけない。
ゆえに、必要ないため、Closeする。

**Comment by tuna2134** [comment]
()
