### ISSUE TITLE
ステータス取得API

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-backend#5]
- シャード稼働状況
  - CPU使用率
  - メモリ使用率
  - サーバー数
  - 人数
  - VPS名?(あまりいらんと思う)

**Comment by tasuren** [comment]
もうある。
https://botdd.alpaca131.com/status/716496407212589087
シャードの数最近減らしたから、何個かオフラインになってるのは仕様。

**Comment by tuna2134** [comment]
cpuとかの

**Comment by tasuren** [comment]
めんどくさいな。

**Comment by tasuren** [comment]
実装した。

**現在の仕様**
`/api/v1/status`にgetでリクエストするとサーバーの稼働状況が返される。
```js
{
  // ↓これをチャンネルと呼ぶ。通常はmainだが、RT Audioの場合はaudioとなる(予定)。
  "Botの起動モード": [
    {
      "discord": {"user": ユーザー数, "guild": サーバー数},
      "performance": {
        "cpu": CPU使用率,
        "memory": [メモリ使用量, 空き容量, 合計]
      }
    }, ...
  ], ...
}
```

**Comment by tasuren** [comment]
色々更新した。(データベース接続数、タスク数、シャード数、そしてバックエンドの動作状況を追加した。)
詳しくはOpenAPIをチェック。
