### ISSUE TITLE
ハートビート実装とシャード管理システムの再構築

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-backend#6]

**Comment by tasuren** [comment]
実装した。

## 設計
### エンドポイント
#### `/api/v1/shards`
このエンドポイント下を使う場合は、Rt認証ヘッダがリクエストにある必要がある。(`Authorization: Rt <署名>`)

**GET**
シャードIDを獲得するためのエンドポイント。
空きがない場合は400エラーとなる。
所謂acquire
**PUT**
シャードをまだ使っていることを伝えるためのエンドポイント。
GET時に貰った署名が必要。
**DELETE**
シャードを手放す際にリクエストすべきエンドポイント。
GET時に貰った署名が必要。
これをすると、手放したシャードIDは再びGETで獲得できるようになる。

#### `/api/v1/shards/ws`
ipcsのウェブソケットのエンドポイント。

### その他
バックエンドが再起動した場合、整合性を保つためにBotは全員再起動する。

### Bot側の適切な実装
起動時に`/api/v1/shards`のgetリクエストを十秒ずつシャードIDを獲得するまで繰り返す。
獲得次第稼働を開始する。
この設計上、予備機であるでない関係なく動作することが保証されているため、予備機の稼働方法は通常と変わらない。
ただ、予備機は全シャードの数を賄えるように稼働すべき。
